services:
  # Контейнер с Node.js
  app:
    build:
      context: ./app
      target: production
    tty: true
    restart: always
    working_dir: /opt/server
    volumes:
      - ./app:/opt/server
      - ./static:/opt/static
      - /opt/server/node_modules/
      - /opt/server/dist/
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      - db

  # Контейнер с базой данных
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always

  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always

  # Контейнер с pgadmin
  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
    expose:
      - '80'
    restart: always
volumes:
  my-postgres-data: